export * from "./Home";
export * from "./hero";
export * from "./social-proof";
export * from "./about";
export * from "./experience";
export * from "./projects";
export * from "./skills";
export * from "./contact";
export * from "./footer";
